<?php
/** @noinspection PhpIncompatibleReturnTypeInspection
 * @noinspection ReturnTypeCanBeDeclaredInspection
 * @noinspection DuplicatedCode
 * @noinspection PhpUnused
 * @noinspection PhpUndefinedMethodInspection
 * @noinspection PhpUnusedLocalVariableInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection NullPointerExceptionInspection
 * @noinspection SenselessProxyMethodInspection
 * @noinspection PhpParameterByRefIsNotUsedAsReferenceInspection
 */
namespace mysql\repomodel;
use eftec\PdoOne;
use Exception;

/**
 * Generated by PdoOne Version 2.8 Date generated Tue, 16 Feb 2021 10:15:08 -0300. 
 * DO NOT EDIT THIS CODE. THIS CODE WILL SELF GENERATE.
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class TableGrandChildTagModel
 * <pre>
 * $code=$pdoOne->generateAbstractModelClass({args});
 * </pre>
 */
abstract class AbstractTableGrandChildTagModel
{
	/** @var int $IdTablaGrandChildTagPK  */
	public $IdTablaGrandChildTagPK;
	/** @var string $Name  */
	public $Name;
	/** @var int $IdgrandchildFK  */
	public $IdgrandchildFK;

	/** @var TableGrandChildModel $_IdgrandchildFK manytoone */
    public $_IdgrandchildFK;


    /**
     * AbstractTableGrandChildTagModel constructor.
     *
     * @param array|null $array
     */
    public function __construct($array=null)
    {
        if($array===null) {
            return;
        }
        foreach($array as $k=>$v) {
            $this->{$k}=$v;
        }
    }

    //<editor-fold desc="array conversion">
    public static function fromArray($array) {
        if($array===null) {
            return null;
        }
        $obj=new TableGrandChildTagModel();
		$obj->IdTablaGrandChildTagPK=isset($array['IdTablaGrandChildTagPK']) ?  $array['IdTablaGrandChildTagPK'] : null;
		$obj->Name=isset($array['Name']) ?  $array['Name'] : null;
		$obj->IdgrandchildFK=isset($array['IdgrandchildFK']) ?  $array['IdgrandchildFK'] : null;
		$obj->_IdgrandchildFK=isset($array['_IdgrandchildFK']) ? 
            $obj->_IdgrandchildFK=TableGrandChildModel::fromArray($array['_IdgrandchildFK']) 
            : null; // manytoone
		($obj->_IdgrandchildFK !== null) 
            and $obj->_IdgrandchildFK->idgrandchildPK=&$obj->IdgrandchildFK; // linked manytoone

        return $obj;
    }
    
    /**
     * It converts the current object in an array
     * 
     * @return mixed
     */
    public function toArray() {
        return static::objectToArray($this);
    }
    
    /**
     * It converts an array of arrays into an array of objects.
     * 
     * @param array|null $array
     *
     * @return array|null
     */
    public static function fromArrayMultiple($array) {
        if($array===null) {
            return null;
        }
        $objs=[];
        foreach($array as $v) {
            $objs[]=self::fromArray($v);
        }
        return $objs;
    }
    //</editor-fold>
    
} // end class