<?php
/** @noinspection PhpUnused */
namespace repo;
use eftec\PdoOne;
use eftec\_BasePdoOneRepo;

/**
 * Generated by PdoOne Version 1.34.1
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne 
 * Class AddressRepo
 */
class AddressRepo extends _BasePdoOneRepo
{
    const TABLE = 'address';
    const PK = 'address_id';
    const ME=__CLASS__;   
    
    public static function getDef() {
        return [
	    'address_id' => 'smallint unsigned not null auto_increment',
	    'address' => 'varchar(50) not null',
	    'address2' => 'varchar(50)',
	    'district' => 'varchar(20) not null',
	    'city_id' => 'smallint unsigned not null',
	    'postal_code' => 'varchar(10)',
	    'phone' => 'varchar(20) not null',
	    'last_update' => 'timestamp not null default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP'
	];
    }
    public static function getDefKey() {
        return [
	    'address_id' => 'PRIMARY KEY',
	    'city_id' => 'KEY'
	];
    }
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [
			    'city_id' => 'FOREIGN KEY REFERENCES`city`(`city_id`) ON UPDATE CASCADE'
			];
        }
        /* key,refcol,reftable,extra */
        return [
		    'city_id' => [
		        'key' => 'FOREIGN KEY',
		        'refcol' => 'city_id',
		        'reftable' => 'city',
		        'extra' => 'FOREIGN KEY REFERENCES`city`(`city_id`) ON UPDATE CASCADE'
		    ],
		    '/store' => [
		        'key' => 'ONETOMANY',
		        'refcol' => 'address_id',
		        'reftable' => 'store',
		        'extra' => ''
		    ]
		];
    }
    public static function factory() {
        $recursive=static::getRecursive();
        return [
		'address_id'=>0,
		'/store'=>(in_array('/store',$recursive))
		                        ? [] 
		                        : null, /* onetomany */
		'address'=>'',
		'address2'=>'',
		'district'=>'',
		'city_id'=>0,
		'/city'=>(in_array('/city',$recursive))
		                    ? cityRepo::factory() 
		                    : null, /* manytoone */
		'postal_code'=>'',
		'phone'=>'',
		'last_update'=>''
		];
    }
    public static function factoryNull() {
        return [
		'address_id'=>null,
		'address'=>null,
		'address2'=>null,
		'district'=>null,
		'city_id'=>null,
		'postal_code'=>null,
		'phone'=>null,
		'last_update'=>null
		];
    }     
     
}