<?php
/** @noinspection PhpUnused */
namespace repo;
use eftec\PdoOne;
use eftec\_BasePdoOneRepo;

/**
 * Generated by PdoOne Version 1.37
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne 
 * Class TablaparentxcategoryRepo
 */
class TablaparentxcategoryRepo extends _BasePdoOneRepo
{
    const TABLE = 'tablaparentxcategory';
    const PK = [
	    'idtablaparentPKFK',
	    'idcategoryPKFK'
	];
    const ME=__CLASS__;   
    
    public static function getDef($onlyKeys=false) {
        $r= [
		    'idtablaparentPKFK' => 'int not null',
		    'idcategoryPKFK' => 'int not null'
		];
        return ($onlyKeys)? array_keys($r): $r;
    }
    public static function getDefKey() {
        return [
	    'idtablaparentPKFK' => 'PRIMARY KEY',
	    'idcategoryPKFK' => 'PRIMARY KEY'
	];
    }
    public static function toList() {
        return self::_toList();
    }
    public static function first($pk = null) {
        return self::_first($pk);
    }
    public static function insert($entity) {
        return self::_insert($entity);
    }
    public static function update($entity) {
        return self::_update($entity);
    }
    public static function delete($entity) {
        return self::_delete($entity);
    }
    public static function deleteById($pk) {
        return self::_deleteById($pk);
    }  
    
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [
			    'idtablaparentPKFK' => 'FOREIGN KEY REFERENCES`tablaParent`(`idtablaparentPK`)',
			    'idcategoryPKFK' => 'FOREIGN KEY REFERENCES`tablacategory`(`IdTablaCategoryPK`)'
			];
        }
        /* key,refcol,reftable,extra */
        return [
		    'idtablaparentPKFK' => [
		        'key' => 'FOREIGN KEY',
		        'refcol' => 'idtablaparentPK',
		        'reftable' => 'tablaParent',
		        'extra' => 'FOREIGN KEY REFERENCES`tablaParent`(`idtablaparentPK`)'
		    ],
		    '/idtablaparentPKFK' => [
		        'key' => 'MANYTOONE',
		        'refcol' => 'idtablaparentPK',
		        'reftable' => 'tablaParent',
		        'extra' => NULL
		    ],
		    'idcategoryPKFK' => [
		        'key' => 'FOREIGN KEY',
		        'refcol' => 'IdTablaCategoryPK',
		        'reftable' => 'tablacategory',
		        'extra' => 'FOREIGN KEY REFERENCES`tablacategory`(`IdTablaCategoryPK`)'
		    ],
		    '/idcategoryPKFK' => [
		        'key' => 'MANYTOONE',
		        'refcol' => 'IdTablaCategoryPK',
		        'reftable' => 'tablacategory',
		        'extra' => NULL
		    ]
		];
    }
    public static function factory() {
        $recursive=static::getRecursive();
        return [
		'idtablaparentPKFK'=>0,
		'/idtablaparentPKFK'=>(in_array('/idtablaparentPKFK',$recursive)) 
		                            ? tablaParentRepo::factory() 
		                            : null, /* manytoone */
		'idcategoryPKFK'=>0,
		'/idcategoryPKFK'=>(in_array('/idcategoryPKFK',$recursive)) 
		                            ? tablacategoryRepo::factory() 
		                            : null, /* manytoone */
		];
    }
    public static function factoryNull() {
        return [
		'idtablaparentPKFK'=>null,
		'/idtablaparentPKFK'=>null, /* manytoone */
		'idcategoryPKFK'=>null,
		'/idcategoryPKFK'=>null, /* manytoone */
		];
    }     
     
}