<?php
/** @noinspection PhpUnused */
namespace repo;
use eftec\PdoOne;
use eftec\_BasePdoOneRepo;

/**
 * Generated by PdoOne Version 1.35
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne 
 * Class TablachildRepo
 */
class TablachildRepo extends _BasePdoOneRepo
{
    const TABLE = 'tablachild';
    const PK = 'idtablachild';
    const ME=__CLASS__;   
    
    public static function getDef() {
        return [
	    'idtablachild' => 'int not null auto_increment',
	    'valuechild' => 'varbinary(50)',
	    'idgrandchildFK' => 'int'
	];
    }
    public static function getDefKey() {
        return [
	    'idtablachild' => 'PRIMARY KEY',
	    'idgrandchildFK' => 'KEY'
	];
    }
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [
			    'idgrandchildFK' => 'FOREIGN KEY REFERENCES`tablagrandchild`(`idgrandchild`)'
			];
        }
        /* key,refcol,reftable,extra */
        return [
		    'idgrandchildFK' => [
		        'key' => 'FOREIGN KEY',
		        'refcol' => 'idgrandchild',
		        'reftable' => 'tablagrandchild',
		        'extra' => 'FOREIGN KEY REFERENCES`tablagrandchild`(`idgrandchild`)'
		    ],
		    '/tablaparent' => [
		        'key' => 'ONETOMANY',
		        'col' => 'idtablachild',
		        'reftable' => 'tablaparent',
		        'refcol' => 'idchild2'
		    ]
		];
    }
    public static function factory() {
        $recursive=static::getRecursive();
        return [
		'idtablachild'=>0,
		'/tablaparent'=>(in_array('/tablaparent',$recursive))
		                        ? [] 
		                        : null, /* onetomany */
		'valuechild'=>'',
		'idgrandchildFK'=>0,
		'/tablagrandchild'=>(in_array('/tablagrandchild',$recursive))
		                    ? tablagrandchildRepo::factory() 
		                    : null, /* manytoone */
		];
    }
    public static function factoryNull() {
        return [
		'idtablachild'=>null,
		'valuechild'=>null,
		'idgrandchildFK'=>null
		];
    }     
     
}