<?php http_response_code(404); die(1); // it is a template, not code, it is protected to be called directly ?>
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
{namespace}
{modelnamespace}
{exception}

/**
 * Class {classname} Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
{helpcolumns}
 * </ul>
 * Generated by PdoOne Version {version}.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo({args});
 * </pre>
{related}
 */
class {classname} extends Abstract{classname}
{
    const ME=__CLASS__;
    {modelclass}


}
