language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
services:
  - mysql
before_script:
  - mysql -e "create database IF NOT EXISTS travisdb;"
  - composer install --no-interaction

script:
  - php vendor/bin/phpunit

