<?php
/** @noinspection PhpUnused */

use eftec\_BasePdoOneRepo;
use eftec\PdoOne;

/**
 * Generated by PdoOne Version 1.31.1
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class ActorRepo
 */
class ActorRepo extends _BasePdoOneRepo
{
    const TABLE = 'actor';
    const PK = 'actor_id';
    const ME=__CLASS__;

    public static function getDef() {
        return [
            "actor_id" => "smallint unsigned not null auto_increment",
            "first_name" => "varchar(45) not null default 'ABC'",
            "last_name" => "varchar(45) not null",
            "last_update" => "timestamp not null default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP"
        ];
    }
    public static function getDefKey() {
        return [
            "actor_id" => "PRIMARY KEY",
            "last_name" => "KEY"
        ];
    }
    public static function getDefFK() {
        return [

        ];
    }
    public static function factory() {
        return ["actor_id"=>0,"first_name"=>null,"last_name"=>'',"last_update"=>''];
    }
    public static function factoryNull() {
        return ["actor_id"=>null,"first_name"=>null,"last_name"=>null,"last_update"=>null];
    }

}