<?php /** @noinspection PhpUnhandledExceptionInspection */

use eftec\PdoOne;

include "../vendor/autoload.php";



// connecting to database sakila at 127.0.0.1 with user root and password abc.123

$pdoOne=new PdoOne('mysql',"127.0.0.1","root","abc.123","termo2","logpdoone.txt");
//$dao = new PdoOne('sqlsrv', "(local)\sqlexpress", "sa", "abc.123", "sakila", "logpdoone.txt");
$pdoOne->logLevel = 3;
$pdoOne->open();

include 'gen/ProducttypesRepo.php';
echo 'Producttypes:';
$result[]=(\eftec\pdoone\ProducttypesRepo::validTable());
include 'gen/ChambertypesRepo.php';
echo 'Chambertypes:';
var_dump(\eftec\pdoone\ChambertypesRepo::validTable());
include 'gen/ProducersRepo.php';
echo 'Producers:';
var_dump(\eftec\pdoone\ProducersRepo::validTable());
include 'gen/FumtipodosisesRepo.php';
echo 'Fumtipodosises:';
var_dump(\eftec\pdoone\FumtipodosisesRepo::validTable());
include 'gen/ChamberuitypesRepo.php';
echo 'Chamberuitypes:';
var_dump(\eftec\pdoone\ChamberuitypesRepo::validTable());
include 'gen/ChamberhistoriesRepo.php';
echo 'Chamberhistories:';
var_dump(\eftec\pdoone\ChamberhistoriesRepo::validTable());
include 'gen/ChambersRepo.php';
echo 'Chambers:';
var_dump(\eftec\pdoone\ChambersRepo::validTable());
include 'gen/ChamberuisRepo.php';
echo 'Chamberuis:';
var_dump(\eftec\pdoone\ChamberuisRepo::validTable());
include 'gen/ConfigsRepo.php';
echo 'Configs:';
var_dump(\eftec\pdoone\ConfigsRepo::validTable());
include 'gen/CountriesRepo.php';
echo 'Countries:';
var_dump(\eftec\pdoone\CountriesRepo::validTable());
include 'gen/FumJobsRepo.php';
echo 'FumJobs:';
var_dump(\eftec\pdoone\FumJobsRepo::validTable());
include 'gen/FumLogsRepo.php';
echo 'FumLogs:';
var_dump(\eftec\pdoone\FumLogsRepo::validTable());
include 'gen/FumcalibresRepo.php';
echo 'Fumcalibres:';
var_dump(\eftec\pdoone\FumcalibresRepo::validTable());
include 'gen/FumenvasesRepo.php';
echo 'Fumenvases:';
var_dump(\eftec\pdoone\FumenvasesRepo::validTable());
include 'gen/FumigationsRepo.php';
echo 'Fumigations:';
var_dump(\eftec\pdoone\FumigationsRepo::validTable());
include 'gen/FummedicionesRepo.php';
echo 'Fummediciones:';
var_dump(\eftec\pdoone\FummedicionesRepo::validTable());
include 'gen/FumpesosRepo.php';
echo 'Fumpesos:';
var_dump(\eftec\pdoone\FumpesosRepo::validTable());
include 'gen/FumproductsRepo.php';
echo 'Fumproducts:';
var_dump(\eftec\pdoone\FumproductsRepo::validTable());
include 'gen/FumtipodosismedicionesRepo.php';
echo 'Fumtipodosismediciones:';
var_dump(\eftec\pdoone\FumtipodosismedicionesRepo::validTable());
include 'gen/FumtipodosisrangosRepo.php';
echo 'Fumtipodosisrangos:';
var_dump(\eftec\pdoone\FumtipodosisrangosRepo::validTable());
include 'gen/MenusRepo.php';
echo 'Menus:';
var_dump(\eftec\pdoone\MenusRepo::validTable());
include 'gen/OpportunitiesRepo.php';
echo 'Opportunities:';
var_dump(\eftec\pdoone\OpportunitiesRepo::validTable());
include 'gen/PlantsRepo.php';
echo 'Plants:';
var_dump(\eftec\pdoone\PlantsRepo::validTable());
include 'gen/ProcesscalibresRepo.php';
echo 'Processcalibres:';
var_dump(\eftec\pdoone\ProcesscalibresRepo::validTable());
include 'gen/ProcesscontainersRepo.php';
echo 'Processcontainers:';
var_dump(\eftec\pdoone\ProcesscontainersRepo::validTable());
include 'gen/ProcesseventsRepo.php';
echo 'Processevents:';
var_dump(\eftec\pdoone\ProcesseventsRepo::validTable());
include 'gen/ProcesshistoriesRepo.php';
echo 'Processhistories:';
var_dump(\eftec\pdoone\ProcesshistoriesRepo::validTable());
include 'gen/ProcesspalletsRepo.php';
echo 'Processpallets:';
var_dump(\eftec\pdoone\ProcesspalletsRepo::validTable());
include 'gen/ProcessproductsRepo.php';
echo 'Processproducts:';
var_dump(\eftec\pdoone\ProcessproductsRepo::validTable());
include 'gen/ProcesstypesRepo.php';
echo 'Processtypes:';
var_dump(\eftec\pdoone\ProcesstypesRepo::validTable());
include 'gen/ProvidersRepo.php';
echo 'Providers:';
var_dump(\eftec\pdoone\ProvidersRepo::validTable());
include 'gen/ReplicationtableRepo.php';
echo 'Replicationtable:';
var_dump(\eftec\pdoone\ReplicationtableRepo::validTable());
include 'gen/SensortypesRepo.php';
echo 'Sensortypes:';
var_dump(\eftec\pdoone\SensortypesRepo::validTable());
include 'gen/SensorsRepo.php';
echo 'Sensors:';
var_dump(\eftec\pdoone\SensorsRepo::validTable());
include 'gen/SensorwritesRepo.php';
echo 'Sensorwrites:';
var_dump(\eftec\pdoone\SensorwritesRepo::validTable());
include 'gen/TestsRepo.php';
echo 'Tests:';
var_dump(\eftec\pdoone\TestsRepo::validTable());
include 'gen/TypeeventsRepo.php';
echo 'Typeevents:';
var_dump(\eftec\pdoone\TypeeventsRepo::validTable());
include 'gen/TypestatuseventsRepo.php';
echo 'Typestatusevents:';
var_dump(\eftec\pdoone\TypestatuseventsRepo::validTable());
include 'gen/UserpermissiontypesRepo.php';
echo 'Userpermissiontypes:';
var_dump(\eftec\pdoone\UserpermissiontypesRepo::validTable());
include 'gen/UsertypesRepo.php';
echo 'Usertypes:';
var_dump(\eftec\pdoone\UsertypesRepo::validTable());
include 'gen/UsersRepo.php';
echo 'Users:';
var_dump(\eftec\pdoone\UsersRepo::validTable());
include 'gen/ProcessesRepo.php';
echo 'Processes:';
var_dump(\eftec\pdoone\ProcessesRepo::validTable());
include 'gen/UsertypexchambersRepo.php';
echo 'Usertypexchambers:';
var_dump(\eftec\pdoone\UsertypexchambersRepo::validTable());
include 'gen/WindowsRepo.php';
echo 'Windows:';
var_dump(\eftec\pdoone\WindowsRepo::validTable());