<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace eftec\tests\sakila2021;

use Exception;
// [EDIT:use] you can edit this part
// Here you can add your custom use
// [/EDIT] end of edit

/**
 * Class FilmRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li>film_id: int (alias of column film_id) </li>
 * <li>title: string (alias of column title) </li>
 * <li>description: binary (alias of column description) </li>
 * <li>release_year: string (alias of column release_year) </li>
 * <li>language_id: int (alias of column language_id) </li>
 * <li>original_language_id: int (alias of column original_language_id) </li>
 * <li>rental_duration: int (alias of column rental_duration) </li>
 * <li>rental_rate: float (alias of column rental_rate) </li>
 * <li>length: int (alias of column length) </li>
 * <li>replacement_cost: float (alias of column replacement_cost) </li>
 * <li>rating: string (alias of column rating) </li>
 * <li>special_features: string (alias of column special_features) </li>
 * <li>last_update: datetime (alias of column last_update) </li>
 * <li>_language_id: MANYTOONE (alias of column _language_id) (LanguageRepoModel)</li>
 * <li>_original_language_id: MANYTOONE (alias of column _original_language_id) (LanguageRepoModel)</li>
 * <li>_film_actor: ONETOMANY (alias of column _film_actor) (FilmActorRepoModel)</li>
 * <li>_film_text: ONETOONE (alias of column _film_text) (FilmTextRepoModel)</li>
 * <li>_inventory: ONETOMANY (alias of column _inventory) (InventoryRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 3.15 Date generated Sat, 11 Feb 2023 18:40:05 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''film'',''eftec\tests\sakila2021'','array('actor'=>'ActorRepo','address'=>'AddresRepo','category'=>'CategoryRepo','city'=>'CityRepo','country'=>'CountryRepo','customer'=>'CustomerRepo','film'=>'FilmRepo','film_actor'=>'FilmActorRepo','film_category'=>'FilmCategoryRepo','film_text'=>'FilmTextRepo','inventory'=>'InventoryRepo','language'=>'LanguageRepo','payment'=>'PaymentRepo','rental'=>'RentalRepo','staff'=>'StaffRepo','store'=>'StoreRepo',)','''','array(0=>array(0=>'film_id',1=>'int',2=>NULL,),1=>array(0=>'title',1=>'string',2=>NULL,),2=>array(0=>'description',1=>'binary',2=>NULL,),3=>array(0=>'release_year',1=>'string',2=>NULL,),4=>array(0=>'language_id',1=>'int',2=>NULL,),5=>array(0=>'original_language_id',1=>'int',2=>NULL,),6=>array(0=>'rental_duration',1=>'int',2=>NULL,),7=>array(0=>'rental_rate',1=>'float',2=>NULL,),8=>array(0=>'length',1=>'int',2=>NULL,),9=>array(0=>'replacement_cost',1=>'float',2=>NULL,),10=>array(0=>'rating',1=>'string',2=>NULL,),11=>array(0=>'special_features',1=>'string',2=>NULL,),12=>array(0=>'last_update',1=>'datetime',2=>NULL,),13=>array(0=>'_language_id',1=>'MANYTOONE',2=>'LanguageRepoModel',),14=>array(0=>'_original_language_id',1=>'MANYTOONE',2=>'LanguageRepoModel',),15=>array(0=>'_film_actor',1=>'ONETOMANY',2=>'FilmActorRepoModel',),16=>array(0=>'_film_text',1=>'ONETOONE',2=>'FilmTextRepoModel',),17=>array(0=>'_inventory',1=>'ONETOMANY',2=>'InventoryRepoModel',),)','array('actor'=>array('actor_id'=>'actor_id','first_name'=>'first_name','last_name'=>'last_name','last_update'=>'last_update','_film_actor'=>'_film_actor',),'address'=>array('address'=>'address','address2'=>'address2','address_id'=>'address_id','city_id'=>'city_id','district'=>'district','last_update'=>'last_update','phone'=>'phone','postal_code'=>'postal_code','_city_id'=>'_city_id','_customer'=>'_customer','_staff'=>'_staff','_store'=>'_store',),'category'=>array('category_id'=>'category_id','last_update'=>'last_update','name'=>'name','_film_category'=>'_film_category',),'city'=>array('city'=>'city','city_id'=>'city_id','country_id'=>'country_id','last_update'=>'last_update','_country_id'=>'_country_id','_address'=>'_address',),'country'=>array('country'=>'country','country_id'=>'country_id','last_update'=>'last_update','_city'=>'_city',),'customer'=>array('active'=>'active','address_id'=>'address_id','create_date'=>'create_date','customer_id'=>'customer_id','email'=>'email','first_name'=>'first_name','last_name'=>'last_name','last_update'=>'last_update','store_id'=>'store_id','_address_id'=>'_address_id','_store_id'=>'_store_id','_payment'=>'_payment','_rental'=>'_rental',),'film'=>array('description'=>'description','film_id'=>'film_id','language_id'=>'language_id','last_update'=>'last_update','length'=>'length','original_language_id'=>'original_language_id','rating'=>'rating','release_year'=>'release_year','rental_duration'=>'rental_duration','rental_rate'=>'rental_rate','replacement_cost'=>'replacement_cost','special_features'=>'special_features','title'=>'title','_language_id'=>'_language_id','_original_language_id'=>'_original_language_id','_film_actor'=>'_film_actor','_film_text'=>'_film_text','_inventory'=>'_inventory',),'film_actor'=>array('actor_id'=>'actor_id','film_id'=>'film_id','last_update'=>'last_update','_actor_id'=>'_actor_id','_film_id'=>'_film_id',),'film_category'=>array('category_id'=>'category_id','film_id'=>'film_id','last_update'=>'last_update','_category_id'=>'_category_id',),'film_text'=>array('description'=>'description','film_id'=>'film_id','title'=>'title','_film_id'=>'_film_id',),'inventory'=>array('film_id'=>'film_id','inventory_id'=>'inventory_id','last_update'=>'last_update','store_id'=>'store_id','_film_id'=>'_film_id','_store_id'=>'_store_id','_rental'=>'_rental',),'language'=>array('language_id'=>'language_id','last_update'=>'last_update','name'=>'name','_film'=>'_film',),'payment'=>array('amount'=>'amount','customer_id'=>'customer_id','last_update'=>'last_update','payment_date'=>'payment_date','payment_id'=>'payment_id','rental_id'=>'rental_id','staff_id'=>'staff_id','_customer_id'=>'_customer_id','_rental_id'=>'_rental_id','_staff_id'=>'_staff_id',),'rental'=>array('customer_id'=>'customer_id','inventory_id'=>'inventory_id','last_update'=>'last_update','rental_date'=>'rental_date','rental_id'=>'rental_id','return_date'=>'return_date','staff_id'=>'staff_id','_customer_id'=>'_customer_id','_inventory_id'=>'_inventory_id','_staff_id'=>'_staff_id','_payment'=>'_payment',),'staff'=>array('active'=>'active','address_id'=>'address_id','email'=>'email','first_name'=>'first_name','last_name'=>'last_name','last_update'=>'last_update','password'=>'password','picture'=>'picture','staff_id'=>'staff_id','store_id'=>'store_id','username'=>'username','_store_id'=>'_store_id','_address_id'=>'_address_id','_payment'=>'_payment','_rental'=>'_rental','_store'=>'_store',),'store'=>array('address_id'=>'address_id','last_update'=>'last_update','manager_staff_id'=>'manager_staff_id','store_id'=>'store_id','_staff'=>'_staff','_address_id'=>'_address_id','_manager_staff_id'=>'_manager_staff_id','_customer'=>'_customer','_inventory'=>'_inventory',),)');
 * </pre>
 * @see LanguageRepoModel
 * @see LanguageRepoModel
 * @see FilmActorRepoModel
 * @see FilmTextRepoModel
 * @see InventoryRepoModel
 */
class FilmRepo extends AbstractFilmRepo
{
    const ME=__CLASS__;
    
    // [EDIT:content] you can edit this part
    // Here you can add your custom content.
    // [/EDIT] end of edit
}
