<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace eftec\examples\clitest\repo2;

use Exception;

/**
 * Class TablegrandchildRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li>idgrandchildPK: int (alias of column idgrandchildPK) </li>
 * <li>NameGrandChild: string (alias of column NameGrandChild) </li>
 * <li>_TableChild: ONETOMANY (alias of column _TableChild) (TablechildRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 2.32.1 Date generated Sun, 22 May 2022 19:29:29 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''TableGrandChild'',''eftec\examples\clitest\repo2'','array('TableCategory'=>'TablecategoryRepo','TableChild'=>'TablechildRepo','TableGrandChild'=>'TablegrandchildRepo','TableGrandChildTag'=>'TablegrandchildtagRepo','TableParent'=>'TableParentRepo','TableParentExt'=>'TableparentextRepo','TableParentxCategory'=>'TableparentxcategoryRepo',)','''','array(0=>array(0=>'idgrandchildPK',1=>'int',2=>NULL,),1=>array(0=>'NameGrandChild',1=>'string',2=>NULL,),2=>array(0=>'_TableChild',1=>'ONETOMANY',2=>'TablechildRepoModel',),)','array('TableCategory'=>array('IdTableCategoryPK'=>'IdTableCategoryPK','Name'=>'Name',),'TableChild'=>array('idgrandchildFK'=>'idgrandchildFK','idtablachildPK'=>'idtablachildPK','NameChild'=>'NameChild',),'TableGrandChild'=>array('idgrandchildPK'=>'idgrandchildPK','NameGrandChild'=>'NameGrandChild',),'TableGrandChildTag'=>array('IdgrandchildFK'=>'IdgrandchildFK','IdTablaGrandChildTagPK'=>'IdTablaGrandChildTagPK','Name'=>'Name',),'TableParent'=>array('fieldDateTime'=>'fieldDateTime','fielDecimal'=>'fielDecimal','fieldInt'=>'fieldInt','fieldKey'=>'FieldKey','fieldUnique'=>'fieldUnique','fieldVarchar'=>'FieldText','idchild2FK'=>'IdChild2Foreign','idchildFK'=>'idchildFK','idtablaparentPK'=>'idtablaparentPK',),'TableParentExt'=>array('fieldExt'=>'fieldExt','idtablaparentExtPK'=>'idtablaparentExtPK',),'TableParentxCategory'=>array('idcategoryPKFK'=>'idcategoryPKFK','idtablaparentPKFK'=>'idtablaparentPKFK',),)');
 * </pre>
 * @see TablechildRepoModel
 */
class TablegrandchildRepo extends AbstractTablegrandchildRepo
{
    const ME=__CLASS__;
    


}
