<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace eftec\examples\clitest\repo2;

use Exception;

/**
 * Class TableparentextRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li>idtablaparentExtPK: int (alias of column idtablaparentExtPK) </li>
 * <li>fieldExt: string (alias of column fieldExt) </li>
 * <li>_idtablaparentExtPK: ONETOONE (alias of column _idtablaparentExtPK) (TableParentRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 2.32.1 Date generated Sun, 22 May 2022 19:29:29 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''TableParentExt'',''eftec\examples\clitest\repo2'','array('TableCategory'=>'TablecategoryRepo','TableChild'=>'TablechildRepo','TableGrandChild'=>'TablegrandchildRepo','TableGrandChildTag'=>'TablegrandchildtagRepo','TableParent'=>'TableParentRepo','TableParentExt'=>'TableparentextRepo','TableParentxCategory'=>'TableparentxcategoryRepo',)','''','array(0=>array(0=>'idtablaparentExtPK',1=>'int',2=>NULL,),1=>array(0=>'fieldExt',1=>'string',2=>NULL,),2=>array(0=>'_idtablaparentExtPK',1=>'ONETOONE',2=>'TableParentRepoModel',),)','array('TableCategory'=>array('IdTableCategoryPK'=>'IdTableCategoryPK','Name'=>'Name',),'TableChild'=>array('idgrandchildFK'=>'idgrandchildFK','idtablachildPK'=>'idtablachildPK','NameChild'=>'NameChild',),'TableGrandChild'=>array('idgrandchildPK'=>'idgrandchildPK','NameGrandChild'=>'NameGrandChild',),'TableGrandChildTag'=>array('IdgrandchildFK'=>'IdgrandchildFK','IdTablaGrandChildTagPK'=>'IdTablaGrandChildTagPK','Name'=>'Name',),'TableParent'=>array('fieldDateTime'=>'fieldDateTime','fielDecimal'=>'fielDecimal','fieldInt'=>'fieldInt','fieldKey'=>'FieldKey','fieldUnique'=>'fieldUnique','fieldVarchar'=>'FieldText','idchild2FK'=>'IdChild2Foreign','idchildFK'=>'idchildFK','idtablaparentPK'=>'idtablaparentPK',),'TableParentExt'=>array('fieldExt'=>'fieldExt','idtablaparentExtPK'=>'idtablaparentExtPK',),'TableParentxCategory'=>array('idcategoryPKFK'=>'idcategoryPKFK','idtablaparentPKFK'=>'idtablaparentPKFK',),)');
 * </pre>
 * @see TableParentRepoModel
 */
class TableparentextRepo extends AbstractTableparentextRepo
{
    const ME=__CLASS__;
    


}
