<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace eftec\examples\clitest\testdb2;

use Exception;

/**
 * Class ProductRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li>Numproduct: int (alias of column IdProducts) </li>
 * <li>Name: string (alias of column Name) </li>
 * <li>City: int (alias of column City) </li>
 * <li>_City: MANYTOONE (alias of column _City) (CityRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 2.32.1 Date generated Sun, 05 Jun 2022 09:16:35 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''products'',''eftec\examples\clitest\testdb2'','array('cities'=>'CityRepo','categories'=>'CategoryRepo','customers'=>'CustomerRepo','customerxcategories'=>'CustomerXCategoryRepo','invoicedetails'=>'InvoicedetailRepo','invoices'=>'InvoiceRepo','products'=>'ProductRepo',)','''','array(0=>array(0=>'IdProducts',1=>'int',2=>NULL,),1=>array(0=>'Name',1=>'string',2=>NULL,),2=>array(0=>'City',1=>'int',2=>NULL,),3=>array(0=>'_City',1=>'MANYTOONE',2=>'CityRepoModel',),)','array('categories'=>array('IdCategory'=>'NumCategory','Name'=>'Name',),'cities'=>array('IdCity'=>'NumCity','Name'=>'NameCity',),'customers'=>array('City'=>'City','Email'=>'Email','IdCustomer'=>'NumCustomer','Name'=>'Name',),'customerxcategories'=>array('Category'=>'Category','Customer'=>'Customer',),'invoicedetails'=>array('IdInvoiceDetail'=>'NumInvoiceDetail','Invoice'=>'Invoice','Product'=>'Product','Quantity'=>'Quantity',),'invoices'=>array('Customer'=>'Customer','Date'=>'Date','IdInvoice'=>'NumInvoice','Total'=>'Total',),'products'=>array('City'=>'City','IdProducts'=>'Numproduct','Name'=>'Name',),)');
 * </pre>
 * @see CityRepoModel
 */
class ProductRepo extends AbstractProductRepo
{
    const ME=__CLASS__;
    


}
