<?php
/** @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace eftec\mini_blog\repo;
use Exception;

/**
 * Generated by PdoOne Version 1.45 Date generated Thu, 11 Jun 2020 16:32:39 -0400. 
 * EDIT THIS CODE.
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class BlogImageRepo
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo('BlogImage','repo','Repo','Dao');
 * </pre>
 */
class BlogImageRepo extends BlogImageDao
{
 
}