<?php
/** @noinspection PhpUnused */
namespace repo;
use eftec\PdoOne;
use eftec\_BasePdoOneRepo;

/**
 * Generated by PdoOne Version 1.39
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne 
 * Class TablaparentExtRepo
 */
class TablaparentExtRepo extends _BasePdoOneRepo
{
    const TABLE = 'tablaparent_ext';
    const PK = [
	    'idtablaparentExtPK'
	];
    const ME=__CLASS__;   
    
    public static function getDef($onlyKeys=false) {
        $r= [
		    'idtablaparentExtPK' => 'int NOT NULL',
		    'field3' => 'varchar(50)'
		];
        return ($onlyKeys)? array_keys($r): $r;
    }
    
    /**
     * It returns an associative array (colname=>key type) with all the keys/indexes (if any)
     * 
     * @return string[]
     */    
    public static function getDefKey() {
        return [
		    'idtablaparentExtPK' => 'PRIMARY KEY'
		];
    }
    public static function getDefIdentity() {
        return [

		];
    }
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [
			    'idtablaparentExtPK' => 'FOREIGN KEY REFERENCES [tablaparent]([idtablaparentPK])'
			];
        }
        /* key,refcol,reftable,extra */
        return [
		    'idtablaparentExtPK' => [
		        'key' => 'FOREIGN KEY',
		        'refcol' => 'idtablaparentPK',
		        'reftable' => 'tablaparent',
		        'extra' => '',
		        'name' => 'FK_tablaparent_ext_tablaparent'
		    ],
		    '/idtablaparentExtPK' => [
		        'key' => 'MANYTOONE',
		        'refcol' => 'idtablaparentPK',
		        'reftable' => 'tablaparent',
		        'extra' => '',
		        'name' => 'FK_tablaparent_ext_tablaparent'
		    ]
		];
    }
    public static function toList($filter=null,$filterValue=null) {
        return self::_toList($filter,$filterValue);
    }
    public static function first($pk = null) {
        return self::_first($pk);
    }
    public static function insert($entity) {
        return self::_insert($entity);
    }
    public static function update($entity) {
        return self::_update($entity);
    }
    public static function delete($filter=null,$filterValue=null) {
        return self::_delete($filter,$filterValue);
    }
    public static function deleteById($pk) {
        return self::_deleteById($pk);
    }  
    

    public static function factory() {
        $recursive=static::getRecursive();
        return [
		'idtablaparentExtPK'=>0,
		'/idtablaparentExtPK'=>(in_array('/idtablaparentExtPK',$recursive)) 
		                            ? tablaparentRepo::factory() 
		                            : null, /* manytoone */
		'field3'=>''
		];
    }
    public static function factoryNull() {
        return [
		'idtablaparentExtPK'=>null,
		'/idtablaparentExtPK'=>null, /* manytoone */
		'field3'=>null
		];
    }     
     
}