<?php
/** @noinspection PhpUnused */
namespace repo;
use eftec\PdoOne;
use eftec\_BasePdoOneRepo;

/**
 * Generated by PdoOne Version 1.37
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne 
 * Class TablaparentRepo
 */
class TablaparentRepo extends _BasePdoOneRepo
{
    const TABLE = 'tablaparent';
    const PK = [
	    'idtablaparentPK'
	];
    const ME=__CLASS__;   
    
    public static function getDef($onlyKeys=false) {
        $r= [
		    'idtablaparentPK' => 'int NOT NULL IDENTITY(1,1)',
		    'field1' => 'varchar(50) DEFAULT (NULL)',
		    'idchildFK' => 'int DEFAULT (NULL)',
		    'idchild2FK' => 'int DEFAULT (NULL)',
		    'field2' => 'varchar(50) DEFAULT (NULL)'
		];
        return ($onlyKeys)? array_keys($r): $r;
    }
    
    /**
     * It returns an associative array (colname=>key type) with all the keys/indexes (if any)
     * 
     * @return string[]
     */    
    public static function getDefKey() {
        return [
		    'idtablaparentPK' => 'PRIMARY KEY',
		    'idchildFK' => 'KEY',
		    'idchild2FK' => 'KEY',
		    'field2' => 'UNIQUE KEY'
		];
    }
    public static function getDefIdentity() {
        return [
		    'idtablaparentPK'
		];
    }
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [
			    'idchild2FK' => 'FOREIGN KEY REFERENCES tablachild(idtablachildPK)',
			    'idchildFK' => 'FOREIGN KEY REFERENCES tablachild(idtablachildPK)'
			];
        }
        /* key,refcol,reftable,extra */
        return [
		    'idchild2FK' => [
		        'key' => 'FOREIGN KEY',
		        'refcol' => 'idtablachildPK',
		        'reftable' => 'tablachild',
		        'extra' => ''
		    ],
		    '/idchild2FK' => [
		        'key' => 'MANYTOONE',
		        'refcol' => 'idtablachildPK',
		        'reftable' => 'tablachild',
		        'extra' => NULL
		    ],
		    'idchildFK' => [
		        'key' => 'FOREIGN KEY',
		        'refcol' => 'idtablachildPK',
		        'reftable' => 'tablachild',
		        'extra' => ''
		    ],
		    '/idchildFK' => [
		        'key' => 'MANYTOONE',
		        'refcol' => 'idtablachildPK',
		        'reftable' => 'tablachild',
		        'extra' => NULL
		    ],
		    '/tablaparentxcategory' => [
		        'key' => 'ONETOMANY',
		        'col' => 'idtablaparentPK',
		        'reftable' => 'tablaparentxcategory',
		        'refcol' => '/idtablaparentPKFK'
		    ]
		];
    }
    public static function toList($filter=null,$filterValue=null) {
        return self::_toList($filter,$filterValue);
    }
    public static function first($pk = null) {
        return self::_first($pk);
    }
    public static function insert($entity) {
        return self::_insert($entity);
    }
    public static function update($entity) {
        return self::_update($entity);
    }
    public static function delete($filter=null,$filterValue=null) {
        return self::_delete($filter,$filterValue);
    }
    public static function deleteById($pk) {
        return self::_deleteById($pk);
    }  
    

    public static function factory() {
        $recursive=static::getRecursive();
        return [
		'idtablaparentPK'=>0,
		'/tablaparentxcategory'=>(in_array('/tablaparentxcategory',$recursive))
		                            ? [] 
		                            : null, /* onetomany */
		'field1'=>'',
		'idchildFK'=>0,
		'/idchildFK'=>(in_array('/idchildFK',$recursive)) 
		                            ? tablachildRepo::factory() 
		                            : null, /* manytoone */
		'idchild2FK'=>0,
		'/idchild2FK'=>(in_array('/idchild2FK',$recursive)) 
		                            ? tablachildRepo::factory() 
		                            : null, /* manytoone */
		'field2'=>''
		];
    }
    public static function factoryNull() {
        return [
		'idtablaparentPK'=>null,
		'/tablaparentxcategory'=>null, /* onetomany */
		'field1'=>null,
		'idchildFK'=>null,
		'/idchildFK'=>null, /* manytoone */
		'idchild2FK'=>null,
		'/idchild2FK'=>null, /* manytoone */
		'field2'=>null
		];
    }     
     
}