<?php
/** @noinspection PhpUnused */
namespace repo;
use eftec\PdoOne;
use eftec\_BasePdoOneRepo;

/**
 * Generated by PdoOne Version 1.37
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne 
 * Class TablagrandchildRepo
 */
class TablagrandchildRepo extends _BasePdoOneRepo
{
    const TABLE = 'tablagrandchild';
    const PK = [
	    'idgrandchildPK'
	];
    const ME=__CLASS__;   
    
    public static function getDef($onlyKeys=false) {
        $r= [
		    'idgrandchildPK' => 'int NOT NULL IDENTITY(1,1)',
		    'NameGrandChild' => 'varchar(50) DEFAULT (NULL)'
		];
        return ($onlyKeys)? array_keys($r): $r;
    }
    
    /**
     * It returns an associative array (colname=>key type) with all the keys/indexes (if any)
     * 
     * @return string[]
     */    
    public static function getDefKey() {
        return [
		    'idgrandchildPK' => 'PRIMARY KEY'
		];
    }
    public static function getDefIdentity() {
        return [
		    'idgrandchildPK'
		];
    }
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [

			];
        }
        /* key,refcol,reftable,extra */
        return [
		    '/tablagrandchildcat' => [
		        'key' => 'ONETOMANY',
		        'col' => 'idgrandchildPK',
		        'reftable' => 'tablagrandchildcat',
		        'refcol' => '/IdgrandchildFK'
		    ],
		    '/tablachild' => [
		        'key' => 'ONETOMANY',
		        'col' => 'idgrandchildPK',
		        'reftable' => 'tablachild',
		        'refcol' => '/idgrandchildFK'
		    ]
		];
    }
    public static function toList($filter=null,$filterValue=null) {
        return self::_toList($filter,$filterValue);
    }
    public static function first($pk = null) {
        return self::_first($pk);
    }
    public static function insert($entity) {
        return self::_insert($entity);
    }
    public static function update($entity) {
        return self::_update($entity);
    }
    public static function delete($filter=null,$filterValue=null) {
        return self::_delete($filter,$filterValue);
    }
    public static function deleteById($pk) {
        return self::_deleteById($pk);
    }  
    

    public static function factory() {
        $recursive=static::getRecursive();
        return [
		'idgrandchildPK'=>0,
		'/tablagrandchildcat'=>(in_array('/tablagrandchildcat',$recursive))
		                            ? [] 
		                            : null, /* onetomany */
		'/tablachild'=>(in_array('/tablachild',$recursive))
		                            ? [] 
		                            : null, /* onetomany */
		'NameGrandChild'=>''
		];
    }
    public static function factoryNull() {
        return [
		'idgrandchildPK'=>null,
		'/tablagrandchildcat'=>null, /* onetomany */
		'/tablachild'=>null, /* onetomany */
		'NameGrandChild'=>null
		];
    }     
     
}