<?php
/** @noinspection PhpUnused */
namespace repo;
use eftec\PdoOne;
use eftec\_BasePdoOneRepo;

/**
 * Generated by PdoOne Version 1.42 Date generated Sun, 31 May 2020 09:58:49 -0400
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne 
 * Class TablaparentRepo
 */
class TablaparentRepo extends _BasePdoOneRepo
{
    const TABLE = 'tablaparent';
    const PK = [
	    'idtablaparentPK'
	];
    const ME=__CLASS__;   
    
    /**
     * It returns the definitions of the columns<br>
     * <b>Example:</b><br>
     * <pre>
     * self::getDef(); // ['colName'=>[php type,php conversion type,type,size,nullable,extra,sql],'colName2'=>..]
     * self::getDef('sql'); // ['colName'=>'sql','colname2'=>'sql2']
     * self::getDef('identity',true); // it returns the columns that are identities ['col1','col2']
     * </pre>
     * <b>PHP Types</b>: binary, date, datetime, decimal,int, string,time, timestamp<br>
     * <b>PHP Conversions</b>: datetime3 (human string), datetime2 (iso), timestamp (int), bool, int, float<br>
     * <b>Param Types</b>: PDO::PARAM_LOB, PDO::PARAM_STR, PDO::PARAM_INT<br>     
     *
     * @param string|null $column =['phptype','conversion','type','size','null','identity','sql'][$i]
     *                             if not null then it only returns the column specified.
     * @param string|null $filter If filter is not null, then it uses the column to filter the result.
     *
     * @return array|array[]
     */    
    public static function getDef($column=null,$filter=null) {
       $r = [
		    'idtablaparentPK' => [
		        'phptype' => 'int',
		        'conversion' => NULL,
		        'type' => 'int',
		        'size' => NULL,
		        'null' => FALSE,
		        'identity' => TRUE,
		        'sql' => 'int NOT NULL IDENTITY(1,1)'
		    ],
		    'field1' => [
		        'phptype' => 'string',
		        'conversion' => NULL,
		        'type' => 'varchar',
		        'size' => '50',
		        'null' => TRUE,
		        'identity' => FALSE,
		        'sql' => 'varchar(50)'
		    ],
		    'idchildFK' => [
		        'phptype' => 'int',
		        'conversion' => NULL,
		        'type' => 'int',
		        'size' => NULL,
		        'null' => TRUE,
		        'identity' => FALSE,
		        'sql' => 'int DEFAULT (NULL)'
		    ],
		    'idchild2FK' => [
		        'phptype' => 'int',
		        'conversion' => NULL,
		        'type' => 'int',
		        'size' => NULL,
		        'null' => TRUE,
		        'identity' => FALSE,
		        'sql' => 'int DEFAULT (NULL)'
		    ],
		    'field2' => [
		        'phptype' => 'string',
		        'conversion' => NULL,
		        'type' => 'varchar',
		        'size' => '50',
		        'null' => TRUE,
		        'identity' => FALSE,
		        'sql' => 'varchar(50)'
		    ],
		    'fieldd' => [
		        'phptype' => 'decimal',
		        'conversion' => NULL,
		        'type' => 'decimal',
		        'size' => '9,2',
		        'null' => TRUE,
		        'identity' => FALSE,
		        'sql' => 'decimal(9,2)'
		    ],
		    'fielddef' => [
		        'phptype' => 'string',
		        'conversion' => NULL,
		        'type' => 'varchar',
		        'size' => '50',
		        'null' => TRUE,
		        'identity' => FALSE,
		        'sql' => 'varchar(50) DEFAULT (\'hi there\')'
		    ]
		];
       if($column!==null) {
            if($filter===null) {
                foreach($r as $k=>$v) {
                    $r[$k]=$v[$column];
                }
            } else {
                $new=[];
                foreach($r as $k=>$v) {
                    if($v[$column]===$filter) {
                        $new[]=$k;
                    }                    
                }
                return $new;
            }
        }
        return $r;        
    }
    
    /**
     * It gets all the name of the columns.
     * 
     * @return string[]
     */
    public static function getDefName() {
        return [
		    'idtablaparentPK',
		    'field1',
		    'idchildFK',
		    'idchild2FK',
		    'field2',
		    'fieldd',
		    'fielddef'
		];
    }
    
    /**
     * It returns an associative array (colname=>key type) with all the keys/indexes (if any)
     * 
     * @return string[]
     */    
    public static function getDefKey() {
        return [
		    'idtablaparentPK' => 'PRIMARY KEY',
		    'idchildFK' => 'KEY',
		    'idchild2FK' => 'KEY',
		    'field2' => 'UNIQUE KEY'
		];
    }
    public static function getDefIdentity() {
        return [
		    'idtablaparentPK'
		];
    }
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [
			    'idchild2FK' => 'FOREIGN KEY REFERENCES [tablachild]([idtablachildPK])',
			    'idchildFK' => 'FOREIGN KEY REFERENCES [tablachild]([idtablachildPK])'
			];
        }
        /* key,refcol,reftable,extra */
        return [
		    'idchild2FK' => [
		        'key' => 'FOREIGN KEY',
		        'refcol' => 'idtablachildPK',
		        'reftable' => 'tablachild',
		        'extra' => '',
		        'name' => 'tablaParent_fk2'
		    ],
		    '/idchild2FK' => [
		        'key' => 'PARENT',
		        'refcol' => 'idtablachildPK',
		        'reftable' => 'tablachild',
		        'extra' => '',
		        'name' => 'tablaParent_fk2'
		    ],
		    'idchildFK' => [
		        'key' => 'FOREIGN KEY',
		        'refcol' => 'idtablachildPK',
		        'reftable' => 'tablachild',
		        'extra' => '',
		        'name' => 'tablaParent_fk1'
		    ],
		    '/idchildFK' => [
		        'key' => 'MANYTOONE',
		        'refcol' => 'idtablachildPK',
		        'reftable' => 'tablachild',
		        'extra' => '',
		        'name' => 'tablaParent_fk1'
		    ],
		    '/tablaparentxcategory' => [
		        'key' => 'MANYTOMANY',
		        'col' => 'idtablaparentPK',
		        'reftable' => 'tablaparentxcategory',
		        'refcol' => '/idtablaparentPKFK',
		        'refcol2' => '/idcategoryPKFK',
		        'col2' => 'IdTablaCategoryPK',
		        'table2' => 'tablacategory'
		    ],
		    '/tablaparent_ext' => [
		        'key' => 'ONETOONE',
		        'col' => 'idtablaparentPK',
		        'reftable' => 'tablaparent_ext',
		        'refcol' => '/idtablaparentExtPK'
		    ]
		];
    }
    public static function toList($filter=null,$filterValue=null) {
        return self::_toList($filter,$filterValue);
    }
    public static function first($pk = null) {
        return self::_first($pk);
    }
    
    /**
     *  It returns true if the entity exists, otherwise false.<br>
     *  <b>Example:</b><br>
     *  <pre>
     *  $this->exist(['id'=>'a1','name'=>'name']); // using an array
     *  $this->exist('a1'); // using the primary key. The table needs a pks and it only works with the first pk.
     *  </pre>     
     *    
     * @param array|mixed $entity=self::factory()
     * @return bool true if the pks exists
     */
    public static function exist($entity) {
        return self::_exist($entity);
    }
    /**
     * @param array $entity=self::factory()
     * @param bool $transactional If true (default) then the operation is transaction
     * @return array|false=self::factory()
     */
    public static function insert(&$entity,$transactional=true) {
        return self::_insert($entity,$transactional);
    }
    
    /**
     * @param array $entity=self::factory()
     * @param bool $transactional If true (default) then the operation is transaction
     * @return array|false=self::factory()
     */
    public static function update($entity,$transactional=true) {
        return self::_update($entity,$transactional);
    }
    public static function delete($entity,$transactional=true) {
        return self::_delete($entity,$transactional);
    }
    public static function deleteById($pk,$transactional=true) {
        return self::_deleteById($pk,$transactional);
    }  
    public static function cleanRowDBtoPHP(&$row) {
        if(isset($row['LastDate'])) {
            $row['LastDate']=PdoOne::dateConvert($row['LastDate'],'sql','human');
        }
        if (isset($row['/IdBlogCategory']) && is_array($row['/IdBlogCategory'])) {
            $class='\\eftec\\mini_blog\\repo\\'.PdoOne::camelize('blogCategory').'Dao';
            $row['/IdBlogCategory']=$class::rowDBtoPHP($row['/IdBlogCategory']);
        }
    }
    public static function cleanRowPHPtoDB(&$row) {
        if(isset($row['LastDate'])) {
            $row['LastDate']=PdoOne::dateConvert($row['LastDate'],'sql','human');
        }
        if (isset($row['/IdBlogCategory']) && is_array($row['/IdBlogCategory'])) {
            $class='\\eftec\\mini_blog\\repo\\'.PdoOne::camelize('blogCategory').'Dao';
            $row['/IdBlogCategory']=$class::rowDBtoPHP($row['/IdBlogCategory']);
        }
    }

    public static function factory() {
        $recursive=static::getRecursive();
        return [
		'idtablaparentPK'=>0,
		'/tablaparentxcategory'=>(in_array('/tablaparentxcategory',$recursive))
		                            ? [] 
		                            : null, /* onetomany */
		'/tablaparent_ext'=>(in_array('/tablaparent_ext',$recursive))
		                            ? [] 
		                            : null, /* onetomany */
		'field1'=>'',
		'idchildFK'=>0,
		'/idchildFK'=>(in_array('/idchildFK',$recursive)) 
		                            ? tablachildRepo::factory() 
		                            : null, /* manytoone */
		'idchild2FK'=>0,
		'/idchild2FK'=>(in_array('/idchild2FK',$recursive)) 
		                            ? tablachildRepo::factory() 
		                            : null, /* manytoone */
		'field2'=>'',
		'fieldd'=>0.0,
		'fielddef'=>''
		];
    }
    public static function factoryNull() {
        return [
		'idtablaparentPK'=>null,
		'/tablaparentxcategory'=>null, /* onetomany */
		'/tablaparent_ext'=>null, /* onetomany */
		'field1'=>null,
		'idchildFK'=>null,
		'/idchildFK'=>null, /* manytoone */
		'idchild2FK'=>null,
		'/idchild2FK'=>null, /* manytoone */
		'field2'=>null,
		'fieldd'=>null,
		'fielddef'=>null
		];
    }     
     
}