<?php
/** @noinspection PhpIncompatibleReturnTypeInspection
 * @noinspection ReturnTypeCanBeDeclaredInspection
 * @noinspection DuplicatedCode
 * @noinspection PhpUnused
 * @noinspection PhpUndefinedMethodInspection
 * @noinspection PhpUnusedLocalVariableInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection NullPointerExceptionInspection
 * @noinspection SenselessProxyMethodInspection
 * @noinspection PhpParameterByRefIsNotUsedAsReferenceInspection
 */
namespace sqlsrv\repomodel;
use eftec\PdoOne;
use Exception;

/**
 * Generated by PdoOne Version 1.50 Date generated Sat, 18 Jul 2020 20:38:59 -0400. 
 * DO NOT EDIT THIS CODE. THIS CODE WILL SELF GENERATE.
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class TableParentExtModel
 * <pre>
 * $code=$pdoOne->generateCodeClass({args});
 * </pre>
 */
class TableParentExtModel
{
	/** @var int $idtablaparentExtPK  */
	public $idtablaparentExtPK;
	/** @var string $fieldExt  */
	public $fieldExt;

	/** @var TableParentModel $_idtablaparentExtPK onetoone */
    public $_idtablaparentExtPK;

    //<editor-fold desc="array conversion">
    public static function fromArray($array) {
        if($array===null) {
            return null;
        }
        $obj=new self();
		$obj->idtablaparentExtPK=isset($array['idtablaparentExtPK']) ?  $array['idtablaparentExtPK'] : null;
		$obj->fieldExt=isset($array['fieldExt']) ?  $array['fieldExt'] : null;
		$obj->_idtablaparentExtPK=isset($array['_idtablaparentExtPK']) ?  
            $obj->_idtablaparentExtPK=TableParentModel::fromArray($array['_idtablaparentExtPK']) 
            : null; // onetoone

        return $obj;
    }
    public function toArray() {
        return (array) $this;
    }
    public static function fromArrayMultiple($array) {
        if($array===null) {
            return null;
        }
        $objs=[];
        foreach($array as $v) {
            $objs[]=self::fromArray($v);
        }
        return $objs;
    }
    //</editor-fold>
    
} // end class