<?php
/** @noinspection PhpUnused */
namespace repo;
use eftec\PdoOne;
use eftec\_BasePdoOneRepo;

/**
 * Generated by PdoOne Version 1.34.1
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne 
 * Class StoreRepo
 */
class StoreRepo extends _BasePdoOneRepo
{
    const TABLE = 'store';
    const PK = 'store_id';
    const ME=__CLASS__;   
    
    public static function getDef() {
        return [
	    'store_id' => ['tinyint unsigned','','not null','default'=>'auto_increment'],
	    'manager_staff_id' => 'int unsigned not null',
	    'address_id' => 'smallint unsigned not null',
	    'last_update' => 'timestamp not null default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP'
	];
    }
    public static function getDefKey() {
        return [
	    'store_id' => 'PRIMARY KEY',
	    'manager_staff_id' => 'UNIQUE KEY',
	    'address_id' => 'KEY'
	];
    }
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [
			    'address_id' => 'FOREIGN KEY REFERENCES`address`(`address_id`) ON UPDATE CASCADE ON DELETE CASCADE',
			    'manager_staff_id' => 'FOREIGN KEY REFERENCES`staff`(`staff_id`) ON UPDATE CASCADE ON DELETE CASCADE'
			];
        }
        /* key,refcol,reftable,extra */
        return [
		    'address_id' => [
		        'key' => 'FOREIGN KEY',
		        'refcol' => 'address_id',
		        'reftable' => 'address',
		        'extra' => 'FOREIGN KEY REFERENCES`address`(`address_id`) ON UPDATE CASCADE ON DELETE CASCADE'
		    ],
		    'manager_staff_id' => [
		        'key' => 'FOREIGN KEY',
		        'refcol' => 'staff_id',
		        'reftable' => 'staff',
		        'extra' => 'FOREIGN KEY REFERENCES`staff`(`staff_id`) ON UPDATE CASCADE ON DELETE CASCADE'
		    ],
		    '/staff' => [
		        'key' => 'ONETOMANY',
		        'refcol' => 'store_id',
		        'reftable' => 'staff',
		        'extra' => ''
		    ]
		];
    }
    public static function factory() {
        $recursive=static::getRecursive();
        return [
		'store_id'=>0,
		'/staff'=>(in_array('/staff',$recursive))
		                        ? [] 
		                        : null, /* onetomany */
		'manager_staff_id'=>0,
		'/staff'=>(in_array('/staff',$recursive))
		                    ? staffRepo::factory() 
		                    : null, /* manytoone */
		'address_id'=>0,
		'/address'=>(in_array('/address',$recursive))
		                    ? addressRepo::factory() 
		                    : null, /* manytoone */
		'last_update'=>''
		];
    }
    public static function factoryNull() {
        return [
		'store_id'=>null,
		'manager_staff_id'=>null,
		'address_id'=>null,
		'last_update'=>null
		];
    }     
     
}