<?php
/** @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace repo;;
use Exception;

/**
 * Generated by PdoOne Version 1.45.1 Date generated Sat, 13 Jun 2020 16:41:00 -0400. 
 * EDIT THIS CODE.
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class TablachildRepo
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''tablachild'',''repo'','array('tablaparent'=>'TablaParentRepo','tablaparent_ext'=>'TablaParentExtRepo','tablachild'=>'TablachildRepo','tablaparentxcategory'=>'TablaparentxcategoryRepo','tablacategory'=>'TablacategoryRepo','tablagrandchildcat'=>'TablagrandchildcatRepo','tablagrandchild'=>'TablagrandchildRepo',)');
 * </pre>
 */
class TablachildRepo extends TablachildRepoExt
{
    const ME=__CLASS__; 
}