<?php
/** @noinspection PhpUnused */
namespace repo;
use eftec\PdoOne;
use eftec\_BasePdoOneRepo;

/**
 * Generated by PdoOne Version 1.40 Date generated Thu, 21 May 2020 18:46:05 -0400
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne 
 * Class TablagrandchildRepo
 */
class TablagrandchildRepo extends _BasePdoOneRepo
{
    const TABLE = 'tablagrandchild';
    const PK = [
	    'idgrandchildPK'
	];
    const ME=__CLASS__;   
    
    public static function getDef($onlyKeys=false) {
        $r= [
		    'idgrandchildPK' => 'int not null auto_increment',
		    'NameGrandChild' => 'varbinary(50)'
		];
        return ($onlyKeys)? array_keys($r): $r;
    }
    
    /**
     * It returns an associative array (colname=>key type) with all the keys/indexes (if any)
     * 
     * @return string[]
     */    
    public static function getDefKey() {
        return [
		    'idgrandchildPK' => 'PRIMARY KEY'
		];
    }
    public static function getDefIdentity() {
        return [
		    'idgrandchildPK'
		];
    }
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [

			];
        }
        /* key,refcol,reftable,extra */
        return [
		    '/tablachild' => [
		        'key' => 'ONETOMANY',
		        'col' => 'idgrandchildPK',
		        'reftable' => 'tablachild',
		        'refcol' => '/idgrandchildFK'
		    ],
		    '/tablagrandchildcat' => [
		        'key' => 'ONETOMANY',
		        'col' => 'idgrandchildPK',
		        'reftable' => 'tablagrandchildcat',
		        'refcol' => '/IdgrandchildFK'
		    ]
		];
    }
    public static function toList($filter=null,$filterValue=null) {
        return self::_toList($filter,$filterValue);
    }
    public static function first($pk = null) {
        return self::_first($pk);
    }
    
    /**
     *  It returns true if the entity exists, otherwise false.<br>
     *  <b>Example:</b><br>
     *  <pre>
     *  $this->exist(['id'=>'a1','name'=>'name']); // using an array
     *  $this->exist('a1'); // using the primary key. The table needs a pks and it only works with the first pk.
     *  </pre>     
     *    
     * @param array|mixed $entity=self::factory()
     * @return bool true if the pks exists
     */
    public static function exist($entity) {
        return self::_exist($entity);
    }
    /**
     * @param array $entity=self::factory()
     * @param bool $transactional If true (default) then the operation is transaction
     * @return array|false=self::factory()
     */
    public static function insert(&$entity,$transactional=true) {
        return self::_insert($entity,$transactional);
    }
    
    /**
     * @param array $entity=self::factory()
     * @param bool $transactional If true (default) then the operation is transaction
     * @return array|false=self::factory()
     */
    public static function update($entity,$transactional=true) {
        return self::_update($entity,$transactional);
    }
    public static function delete($entity,$transactional=true) {
        return self::_delete($entity,$transactional);
    }
    public static function deleteById($pk,$transactional=true) {
        return self::_deleteById($pk,$transactional);
    }  
    

    public static function factory() {
        $recursive=static::getRecursive();
        return [
		'idgrandchildPK'=>0,
		'/tablachild'=>(in_array('/tablachild',$recursive))
		                            ? [] 
		                            : null, /* onetomany */
		'/tablagrandchildcat'=>(in_array('/tablagrandchildcat',$recursive))
		                            ? [] 
		                            : null, /* onetomany */
		'NameGrandChild'=>''
		];
    }
    public static function factoryNull() {
        return [
		'idgrandchildPK'=>null,
		'/tablachild'=>null, /* onetomany */
		'/tablagrandchildcat'=>null, /* onetomany */
		'NameGrandChild'=>null
		];
    }     
     
}