<?php
/** @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace repo;;
use Exception;

/**
 * Generated by PdoOne Version 1.48 Date generated Fri, 19 Jun 2020 09:00:37 -0400. 
 * EDIT THIS CODE.
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class TablagrandchildRepo
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''tablagrandchild'',''repo'','array('tablaparent'=>'TablaParentRepo','tablachild'=>'TablachildRepo','tablaparentxcategory'=>'TablaparentxcategoryRepo','tablacategory'=>'TablacategoryRepo','tablagrandchildcat'=>'TablagrandchildcatRepo','tablagrandchild'=>'TablagrandchildRepo',)');
 * </pre>
 */
class TablagrandchildRepo extends TablagrandchildRepoExt
{
    const ME=__CLASS__; 
}