<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace eftec\examples\clitest\repo2;

use Exception;

/**
 * Class DummytableRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li>iddummytable int </li>
 * <li>dummytablecol string </li>
 * <li>dummytablecol1 string </li>
 * <li>dummytablecol2 datetime </li>
 * <li>dummytablecol3 float </li>
 * <li>dummytablecol4 binary </li>
 * <li>dummytablecol5 date </li>
 * <li>dummytablecol6 timestamp </li>
 * <li>dummytablecol7 binary </li>
 * <li>dummytablecol8 string </li>
 * <li>dummytablecol9 string </li>
 * <li>dummytablecol10 int </li>
 * <li>dummytablecol11 string </li>
 * <li>dummytablecol12 string </li>
 * <li>dummytablecol13 string </li>
 * <li>dummytablecol14 float </li>
 * <li>dummytablecol15 float </li>
 * <li>dummytablecol16 time </li>
 * <li>dummytablecol17 string </li>
 * </ul>
 * Generated by PdoOne Version 2.27 Date generated Mon, 28 Feb 2022 00:10:18 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''dummytable'',''eftec\examples\clitest\repo2'','array('actor'=>'ActorRepo','actor2'=>'Actor2Repo','address'=>'AddresRepo','category'=>'CategoryRepo','city'=>'CityRepo','country'=>'CountryRepo','customer'=>'CustomerRepo','dummyt'=>'DummytRepo','dummytable'=>'DummytableRepo','film'=>'FilmRepo','film2'=>'Film2Repo','film_actor'=>'FilmActorRepo','film_category'=>'FilmCategoryRepo','film_text'=>'FilmTextRepo','fum_jobs'=>'FumJobRepo','fum_logs'=>'FumLogRepo','inventory'=>'InventoryRepo','language'=>'LanguageRepo','mysec_table'=>'MysecTableRepo','payment'=>'PaymentRepo','product'=>'ProductRepo','producttype'=>'ProducttypeRepo','producttype_auto'=>'ProducttypeAutoRepo','rental'=>'RentalRepo','staff'=>'StaffRepo','store'=>'StoreRepo','tablachild'=>'TablachildRepo','tablagrandchild'=>'TablagrandchildRepo','tablaparent'=>'TablaparentRepo','tabletest'=>'TabletestRepo','test_products'=>'TestProductRepo','typetable'=>'TypetableRepo',)','''','array(0=>array(0=>'iddummytable',1=>'int',2=>NULL,),1=>array(0=>'dummytablecol',1=>'string',2=>NULL,),2=>array(0=>'dummytablecol1',1=>'string',2=>NULL,),3=>array(0=>'dummytablecol2',1=>'datetime',2=>NULL,),4=>array(0=>'dummytablecol3',1=>'float',2=>NULL,),5=>array(0=>'dummytablecol4',1=>'binary',2=>NULL,),6=>array(0=>'dummytablecol5',1=>'date',2=>NULL,),7=>array(0=>'dummytablecol6',1=>'timestamp',2=>NULL,),8=>array(0=>'dummytablecol7',1=>'binary',2=>NULL,),9=>array(0=>'dummytablecol8',1=>'string',2=>NULL,),10=>array(0=>'dummytablecol9',1=>'string',2=>NULL,),11=>array(0=>'dummytablecol10',1=>'int',2=>NULL,),12=>array(0=>'dummytablecol11',1=>'string',2=>NULL,),13=>array(0=>'dummytablecol12',1=>'string',2=>NULL,),14=>array(0=>'dummytablecol13',1=>'string',2=>NULL,),15=>array(0=>'dummytablecol14',1=>'float',2=>NULL,),16=>array(0=>'dummytablecol15',1=>'float',2=>NULL,),17=>array(0=>'dummytablecol16',1=>'time',2=>NULL,),18=>array(0=>'dummytablecol17',1=>'string',2=>NULL,),)');
 * </pre>

 */
class DummytableRepo extends AbstractDummytableRepo
{
    const ME=__CLASS__;
    


}
