<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace eftec\examples\clitest\repo2;

use Exception;

/**
 * Class FilmRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li>film_id int </li>
 * <li>title string </li>
 * <li>description binary </li>
 * <li>release_year int </li>
 * <li>language_id int </li>
 * <li>original_language_id int </li>
 * <li>rental_duration int </li>
 * <li>rental_rate float </li>
 * <li>length int </li>
 * <li>replacement_cost float </li>
 * <li>rating string </li>
 * <li>special_features string </li>
 * <li>last_update timestamp </li>
 * <li>_language_id MANYTOONE (LanguageRepoModel)</li>
 * <li>_original_language_id MANYTOONE (LanguageRepoModel)</li>
 * <li>_film_actor ONETOMANY (FilmActorRepoModel)</li>
 * <li>_film_category ONETOMANY (FilmCategoryRepoModel)</li>
 * <li>_inventory ONETOMANY (InventoryRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 2.27 Date generated Mon, 28 Feb 2022 00:10:18 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''film'',''eftec\examples\clitest\repo2'','array('actor'=>'ActorRepo','actor2'=>'Actor2Repo','address'=>'AddresRepo','category'=>'CategoryRepo','city'=>'CityRepo','country'=>'CountryRepo','customer'=>'CustomerRepo','dummyt'=>'DummytRepo','dummytable'=>'DummytableRepo','film'=>'FilmRepo','film2'=>'Film2Repo','film_actor'=>'FilmActorRepo','film_category'=>'FilmCategoryRepo','film_text'=>'FilmTextRepo','fum_jobs'=>'FumJobRepo','fum_logs'=>'FumLogRepo','inventory'=>'InventoryRepo','language'=>'LanguageRepo','mysec_table'=>'MysecTableRepo','payment'=>'PaymentRepo','product'=>'ProductRepo','producttype'=>'ProducttypeRepo','producttype_auto'=>'ProducttypeAutoRepo','rental'=>'RentalRepo','staff'=>'StaffRepo','store'=>'StoreRepo','tablachild'=>'TablachildRepo','tablagrandchild'=>'TablagrandchildRepo','tablaparent'=>'TablaparentRepo','tabletest'=>'TabletestRepo','test_products'=>'TestProductRepo','typetable'=>'TypetableRepo',)','''','array(0=>array(0=>'film_id',1=>'int',2=>NULL,),1=>array(0=>'title',1=>'string',2=>NULL,),2=>array(0=>'description',1=>'binary',2=>NULL,),3=>array(0=>'release_year',1=>'int',2=>NULL,),4=>array(0=>'language_id',1=>'int',2=>NULL,),5=>array(0=>'original_language_id',1=>'int',2=>NULL,),6=>array(0=>'rental_duration',1=>'int',2=>NULL,),7=>array(0=>'rental_rate',1=>'float',2=>NULL,),8=>array(0=>'length',1=>'int',2=>NULL,),9=>array(0=>'replacement_cost',1=>'float',2=>NULL,),10=>array(0=>'rating',1=>'string',2=>NULL,),11=>array(0=>'special_features',1=>'string',2=>NULL,),12=>array(0=>'last_update',1=>'timestamp',2=>NULL,),13=>array(0=>'_language_id',1=>'MANYTOONE',2=>'LanguageRepoModel',),14=>array(0=>'_original_language_id',1=>'MANYTOONE',2=>'LanguageRepoModel',),15=>array(0=>'_film_actor',1=>'ONETOMANY',2=>'FilmActorRepoModel',),16=>array(0=>'_film_category',1=>'ONETOMANY',2=>'FilmCategoryRepoModel',),17=>array(0=>'_inventory',1=>'ONETOMANY',2=>'InventoryRepoModel',),)');
 * </pre>
 * @see LanguageRepoModel
 * @see LanguageRepoModel
 * @see FilmActorRepoModel
 * @see FilmCategoryRepoModel
 * @see InventoryRepoModel
 */
class FilmRepo extends AbstractFilmRepo
{
    const ME=__CLASS__;
    


}
