<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace eftec\examples\clitest\repo2;

use Exception;

/**
 * Class PaymentRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li>payment_id int </li>
 * <li>customer_id int </li>
 * <li>staff_id int </li>
 * <li>rental_id int </li>
 * <li>amount float </li>
 * <li>payment_date datetime </li>
 * <li>last_update timestamp </li>
 * <li>_customer_id MANYTOONE (CustomerRepoModel)</li>
 * <li>_rental_id MANYTOONE (RentalRepoModel)</li>
 * <li>_staff_id MANYTOONE (StaffRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 2.27 Date generated Mon, 28 Feb 2022 00:10:18 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''payment'',''eftec\examples\clitest\repo2'','array('actor'=>'ActorRepo','actor2'=>'Actor2Repo','address'=>'AddresRepo','category'=>'CategoryRepo','city'=>'CityRepo','country'=>'CountryRepo','customer'=>'CustomerRepo','dummyt'=>'DummytRepo','dummytable'=>'DummytableRepo','film'=>'FilmRepo','film2'=>'Film2Repo','film_actor'=>'FilmActorRepo','film_category'=>'FilmCategoryRepo','film_text'=>'FilmTextRepo','fum_jobs'=>'FumJobRepo','fum_logs'=>'FumLogRepo','inventory'=>'InventoryRepo','language'=>'LanguageRepo','mysec_table'=>'MysecTableRepo','payment'=>'PaymentRepo','product'=>'ProductRepo','producttype'=>'ProducttypeRepo','producttype_auto'=>'ProducttypeAutoRepo','rental'=>'RentalRepo','staff'=>'StaffRepo','store'=>'StoreRepo','tablachild'=>'TablachildRepo','tablagrandchild'=>'TablagrandchildRepo','tablaparent'=>'TablaparentRepo','tabletest'=>'TabletestRepo','test_products'=>'TestProductRepo','typetable'=>'TypetableRepo',)','''','array(0=>array(0=>'payment_id',1=>'int',2=>NULL,),1=>array(0=>'customer_id',1=>'int',2=>NULL,),2=>array(0=>'staff_id',1=>'int',2=>NULL,),3=>array(0=>'rental_id',1=>'int',2=>NULL,),4=>array(0=>'amount',1=>'float',2=>NULL,),5=>array(0=>'payment_date',1=>'datetime',2=>NULL,),6=>array(0=>'last_update',1=>'timestamp',2=>NULL,),7=>array(0=>'_customer_id',1=>'MANYTOONE',2=>'CustomerRepoModel',),8=>array(0=>'_rental_id',1=>'MANYTOONE',2=>'RentalRepoModel',),9=>array(0=>'_staff_id',1=>'MANYTOONE',2=>'StaffRepoModel',),)');
 * </pre>
 * @see CustomerRepoModel
 * @see RentalRepoModel
 * @see StaffRepoModel
 */
class PaymentRepo extends AbstractPaymentRepo
{
    const ME=__CLASS__;
    


}
