<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace eftec\examples\clitest\repo2;

use Exception;

/**
 * Class TablaparentRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li>idtablaparent int </li>
 * <li>field1 string </li>
 * <li>idchild int </li>
 * <li>idchild2 int </li>
 * <li>_idchild MANYTOONE (TablachildRepoModel)</li>
 * <li>_idchild2 MANYTOONE (TablachildRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 2.27 Date generated Mon, 28 Feb 2022 00:10:18 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''tablaparent'',''eftec\examples\clitest\repo2'','array('actor'=>'ActorRepo','actor2'=>'Actor2Repo','address'=>'AddresRepo','category'=>'CategoryRepo','city'=>'CityRepo','country'=>'CountryRepo','customer'=>'CustomerRepo','dummyt'=>'DummytRepo','dummytable'=>'DummytableRepo','film'=>'FilmRepo','film2'=>'Film2Repo','film_actor'=>'FilmActorRepo','film_category'=>'FilmCategoryRepo','film_text'=>'FilmTextRepo','fum_jobs'=>'FumJobRepo','fum_logs'=>'FumLogRepo','inventory'=>'InventoryRepo','language'=>'LanguageRepo','mysec_table'=>'MysecTableRepo','payment'=>'PaymentRepo','product'=>'ProductRepo','producttype'=>'ProducttypeRepo','producttype_auto'=>'ProducttypeAutoRepo','rental'=>'RentalRepo','staff'=>'StaffRepo','store'=>'StoreRepo','tablachild'=>'TablachildRepo','tablagrandchild'=>'TablagrandchildRepo','tablaparent'=>'TablaparentRepo','tabletest'=>'TabletestRepo','test_products'=>'TestProductRepo','typetable'=>'TypetableRepo',)','''','array(0=>array(0=>'idtablaparent',1=>'int',2=>NULL,),1=>array(0=>'field1',1=>'string',2=>NULL,),2=>array(0=>'idchild',1=>'int',2=>NULL,),3=>array(0=>'idchild2',1=>'int',2=>NULL,),4=>array(0=>'_idchild',1=>'MANYTOONE',2=>'TablachildRepoModel',),5=>array(0=>'_idchild2',1=>'MANYTOONE',2=>'TablachildRepoModel',),)');
 * </pre>
 * @see TablachildRepoModel
 * @see TablachildRepoModel
 */
class TablaparentRepo extends AbstractTablaparentRepo
{
    const ME=__CLASS__;
    


}
