<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace eftec\examples\clitest\repo2;

use Exception;

/**
 * Class TablachildRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li>idtablachild int </li>
 * <li>valuechild binary </li>
 * <li>idgrandchildFK int </li>
 * <li>_idgrandchildFK MANYTOONE (TablagrandchildRepoModel)</li>
 * <li>_tablaparent ONETOMANY (TablaparentRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 2.27 Date generated Mon, 28 Feb 2022 00:10:18 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''tablachild'',''eftec\examples\clitest\repo2'','array('actor'=>'ActorRepo','actor2'=>'Actor2Repo','address'=>'AddresRepo','category'=>'CategoryRepo','city'=>'CityRepo','country'=>'CountryRepo','customer'=>'CustomerRepo','dummyt'=>'DummytRepo','dummytable'=>'DummytableRepo','film'=>'FilmRepo','film2'=>'Film2Repo','film_actor'=>'FilmActorRepo','film_category'=>'FilmCategoryRepo','film_text'=>'FilmTextRepo','fum_jobs'=>'FumJobRepo','fum_logs'=>'FumLogRepo','inventory'=>'InventoryRepo','language'=>'LanguageRepo','mysec_table'=>'MysecTableRepo','payment'=>'PaymentRepo','product'=>'ProductRepo','producttype'=>'ProducttypeRepo','producttype_auto'=>'ProducttypeAutoRepo','rental'=>'RentalRepo','staff'=>'StaffRepo','store'=>'StoreRepo','tablachild'=>'TablachildRepo','tablagrandchild'=>'TablagrandchildRepo','tablaparent'=>'TablaparentRepo','tabletest'=>'TabletestRepo','test_products'=>'TestProductRepo','typetable'=>'TypetableRepo',)','''','array(0=>array(0=>'idtablachild',1=>'int',2=>NULL,),1=>array(0=>'valuechild',1=>'binary',2=>NULL,),2=>array(0=>'idgrandchildFK',1=>'int',2=>NULL,),3=>array(0=>'_idgrandchildFK',1=>'MANYTOONE',2=>'TablagrandchildRepoModel',),4=>array(0=>'_tablaparent',1=>'ONETOMANY',2=>'TablaparentRepoModel',),)');
 * </pre>
 * @see TablagrandchildRepoModel
 * @see TablaparentRepoModel
 */
class TablachildRepo extends AbstractTablachildRepo
{
    const ME=__CLASS__;
    


}
